### ISSUE TITLE
Option to make items "fixed" but not required

### ISSUE THREAD

**Issue by rolandtoth** [voorhoede/datocms-plugin-json-table#7]
Thank you for the plugin, we are using it for some models because this is the only one that allows creating key-value pairs easily, without taking up much admin space.

However, it would be handy if there would be an option to add "fixed" items, but without the need to make them required, as of now. With this, content editors could be provided with a fixed set of keys, and they could just fill in the values they need (not all of them).

I could imagine eg. modifying the "Required fields" list so that if a field eg. ends with a question mark, it would mean that it's a field that is optional, but would still show up initially.

It could be a nice addition imo, but let me know if I should create a PR for this (not sure when will I be able to though).

**Comment by velomovies** [comment]
Hi @rolandtoth,
Sorry for the wait. Nice addition! We have added it here https://github.com/voorhoede/datocms-plugin-json-table/pull/8. Once dato has pick it up you can update the plugin to version `v2.1.0` and you should be able to have non-editable optional fields by adding a `?` behind one of the items

**Comment by velomovies** [comment]
I will close this issue since Dato has published the new version. https://www.datocms.com/marketplace/plugins/i/datocms-plugin-json-table

**Comment by rolandtoth** [comment]
Thank you, just noticed the update. I'll check soon.
